version: 2.1

orbs:
  pr-comment: benjlevesque/pr-comment@0.1.0

jobs:
  build:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - pr-comment/pr-comment:
          comment: "Hello"

workflows:
  version: 2
  build:
    jobs:
      - build